<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-HU9II26B" failures="1" tests="5" name="com.cucmber.pratice.com.cucumber.RunnerClass" time="20.504" errors="0" timestamp="16 Apr 2024 21:11:13 GMT">
  <testcase classname="com.cucmber.pratice.com.cucumber.RunnerClass" name="SubmitOrder" time="13.866"/>
  <testcase classname="com.cucmber.pratice.com.cucumber.RunnerClass" name="SubmitOrderforedge3" time="0.002"/>
  <testcase classname="com.cucmber.pratice.com.cucumber.RunnerClass" name="SubmitOrderforedge" time="6.633">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.cucmber.pratice.com.cucumber.RunnerClass.SubmitOrderforedge(RunnerClass.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- SubmitOrderforedge -->
  <testcase classname="com.cucmber.pratice.com.cucumber.RunnerClass" name="SubmitOrderforedge1" time="0.001"/>
  <testcase classname="com.cucmber.pratice.com.cucumber.RunnerClass" name="SubmitOrderforedge2" time="0.002"/>
</testsuite> <!-- com.cucmber.pratice.com.cucumber.RunnerClass -->
